index:
   path: /
   controller: App\Controller\HomeController::index
addProduct:
      path: /new
      controller: App\Controller\HomeController::new
page:
      path: /page/{pageName}
      controller: App\Controller\HomeController::page
